include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable some overly strict rules for development
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
