name: nofapp
description: nofApp - Clean, modern Material 3 app with streaks, medals, and guilds

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.5.1

  # Navigation
  go_router: ^14.6.2

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

  # RevenueCat
  purchases_flutter: ^9.6.2

  # UI Components
  cupertino_icons: ^1.0.8

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.1
  shared_preferences: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code Generation
  riverpod_generator: ^2.5.1
  build_runner: ^2.4.13
  json_annotation: ^4.9.0
  json_serializable: ^6.9.2

  # Icons
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/android/android light mode.png"
  image_path_ios: "assets/icons/ios/ios light mode.png"
  adaptive_icon_background: "#111111"
  adaptive_icon_foreground: "assets/icons/android/android light mode.png"

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/avatars/female/
    - assets/avatars/male/
    - assets/avatars/premium/
    - assets/medals/personal/normal/
    - assets/medals/personal/small/
    - assets/medals/guild/normal/guild medals/
    - assets/medals/guild/small/
    - assets/icons/ios/
    - assets/icons/android/
