// Sample secrets file for nofApp
// Copy this to lib/secrets.dart and add your actual keys
// lib/secrets.dart should be added to .gitignore

class Secrets {
  // RevenueCat API Keys
  // Get these from RevenueCat Dashboard > Project Settings > API Keys
  static const String revenueCatAndroidKey = 'rc_android_key_here';
  static const String revenueCatIosKey = 'rc_ios_key_here';
  
  // Firebase configuration will be in firebase_options.dart (generated by FlutterFire CLI)
  
  // Premium product identifiers (these should match RevenueCat configuration)
  static const String premiumMonthlyProductId = 'nofapp_premium_monthly';
  static const String premiumAnnualProductId = 'nofapp_premium_yearly';
  
  // Development flags
  static const bool isDevelopmentMode = bool.fromEnvironment('DEVELOPMENT', defaultValue: true);
  static const bool mockPremiumFeatures = bool.fromEnvironment('MOCK_PREMIUM', defaultValue: false);
  
  // Helper methods
  static bool get hasRevenueCatKeys => 
      revenueCatAndroidKey != 'rc_android_key_here' && 
      revenueCatIosKey != 'rc_ios_key_here';
      
  static bool get isProductionMode => !isDevelopmentMode;
}

// Instructions for setup:
// 1. Copy this file to lib/secrets.dart
// 2. Replace the placeholder keys with actual RevenueCat keys
// 3. Ensure lib/secrets.dart is in .gitignore
// 4. For CI/CD, use --dart-define instead:
//    flutter run --dart-define=RC_ANDROID=xxx --dart-define=RC_IOS=yyy